#
# Nymph configuration file
#
debug: false
npc:
  Nymph:
    skin:
      name: "skin891679459"
      uuid: "a38e8c4a-b33b-4d7c-af73-e631a337ff41"
      texture: "eyJ0aW1lc3RhbXAiOjE1NTgxMjYxMzI3MTEsInByb2ZpbGVJZCI6IjNmYzdmZGY5Mzk2MzRjNDE5MTE5OWJhM2Y3Y2MzZmVkIiwicHJvZmlsZU5hbWUiOiJZZWxlaGEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2E0ZmRiMjE2ZTJkYTIyZGVlN2Q1ZTU2ZGJjNTg0Mzc2ODFlY2U1MmFlMjc5NTg1MTAyN2ExMGNjODY0ZDVjYWYifX19"
      signature: "yg0uHgH0fBecX7I3ht7asCMJWwKpZhJGCwmVu0VODKNmR5BF7tBfkgPc/P1D/HFeDW4FxpZdUYOypP6yl3E/KPenH1aT/jAkG4L7DRvRyRjZZDzW310K5WK2YSihTEFO5VEyrXhQ+vMdh7iCYZo8uHtppUfJOCeb4ogze/m9ne9JtDMRrgKBhCrF0rnVGmqq2V5BG1erP2lLJ8qI5HMNS4ItNrmN8HJcxVHssceeVW5IoulwVdlXLtT0wudktur4DVLbS+c/g4Y5+c3zUhLU4Uk8wnD94HJ2wu+S1bmZPYbHZND8zgomg/0zCjTzRehQgs4rRqC/AVMpf7DTBtiA44LGeMpeecbg+FCS+uCWhNg8NwasdB3uwRpdcoAYkIWVWccxazrr0P91CYqm48b8AUJKB5qNJZJpXpjbV7j06FwzqSWVXXeWLmv50Icso9HjEkiRtmKKy2vytD/2cc3EsAdMmdtOFVrKePc4GXBe8v/Re0LQDo1PqDjaZ1QGp6sHduW43zX9dgwbDSRM+ZBfg1axo53O8axNiXJCFzyu5fQImqiTpqVDi9AY6D9RKrp2QUSiX6BSjHoV+q6N5qpqcZYP7/fFU0qII8HrIPb4RTvnh9h9aLIIVHNuC59uZk0mnofPWSs7QU8i6LyrAZMa55QPOMms9xe/Mmp2Qy41BBs="
